fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Recon\ModelBundle\Entity\User
    registration:
        confirmation:
            enabled:    false
    from_email:
        address:        %email_from%
        sender_name:    Quick Survey